import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Homepage from './homepage/homepage'
import NavBar from './nav/nav'
import HomepageText from './homepage/homepageText'
import Demonstration from './demonstration/demonstration'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <header className='absolute w-full pt-5'>
          <NavBar></NavBar> 
        </header>
        <div className=''>
          <Homepage></Homepage>
        </div>

        <div className='h-[100vh]'>
          <Demonstration></Demonstration>
        </div>
      </main>
    </>
  )
}
